// Mandarin radicals dataset
// radical : the standalone radical
// variant : how the radical looks as a component inside characters (= radical when unchanged)
// example : a common character that contains the radical, showing the component in context
const RADICALS = [
  { radical: "水", pinyin: "shuǐ", meaning: "water", variant: "氵", example: { char: "海", pinyin: "hǎi", meaning: "sea" } },
  { radical: "艹", pinyin: "cǎo", meaning: "grass", variant: "艹", example: { char: "花", pinyin: "huā", meaning: "flower" } },
  { radical: "口", pinyin: "kǒu", meaning: "mouth", variant: "口", example: { char: "吃", pinyin: "chī", meaning: "eat" } },
  { radical: "木", pinyin: "mù", meaning: "wood", variant: "木", example: { char: "林", pinyin: "lín", meaning: "forest" } },
  { radical: "手", pinyin: "shǒu", meaning: "hand", variant: "扌", example: { char: "打", pinyin: "dǎ", meaning: "hit" } },
  { radical: "人", pinyin: "rén", meaning: "people/person", variant: "亻", example: { char: "你", pinyin: "nǐ", meaning: "you" } },
  { radical: "金", pinyin: "jīn", meaning: "metal", variant: "钅", example: { char: "银", pinyin: "yín", meaning: "silver" } },
  { radical: "心", pinyin: "xīn", meaning: "heart", variant: "忄", example: { char: "忙", pinyin: "máng", meaning: "busy" } },
  { radical: "土", pinyin: "tǔ", meaning: "soil", variant: "土", example: { char: "地", pinyin: "dì", meaning: "ground" } },
  { radical: "月", pinyin: "yuè", meaning: "moon", variant: "月", example: { char: "明", pinyin: "míng", meaning: "bright" } },
  { radical: "糸", pinyin: "mì", meaning: "silk", variant: "纟", example: { char: "红", pinyin: "hóng", meaning: "red" } },
  { radical: "虫", pinyin: "chóng", meaning: "insect", variant: "虫", example: { char: "虾", pinyin: "xiā", meaning: "shrimp" } },
  { radical: "言", pinyin: "yán", meaning: "speech", variant: "讠", example: { char: "说", pinyin: "shuō", meaning: "speak" } },
  { radical: "女", pinyin: "nǚ", meaning: "female", variant: "女", example: { char: "妈", pinyin: "mā", meaning: "mom" } },
  { radical: "竹", pinyin: "zhú", meaning: "bamboo", variant: "竹", example: { char: "笔", pinyin: "bǐ", meaning: "pen" } },
  { radical: "火", pinyin: "huǒ", meaning: "fire", variant: "灬", example: { char: "热", pinyin: "rè", meaning: "hot" } },
  { radical: "王", pinyin: "wáng", meaning: "king", variant: "王", example: { char: "玩", pinyin: "wán", meaning: "play" } },
  { radical: "日", pinyin: "rì", meaning: "sun", variant: "日", example: { char: "时", pinyin: "shí", meaning: "time" } },
  { radical: "石", pinyin: "shí", meaning: "stone", variant: "石", example: { char: "硬", pinyin: "yìng", meaning: "hard" } },
  { radical: "鱼", pinyin: "yú", meaning: "fish", variant: "鱼", example: { char: "鲜", pinyin: "xiān", meaning: "fresh" } },
  { radical: "山", pinyin: "shān", meaning: "mountain", variant: "山", example: { char: "峰", pinyin: "fēng", meaning: "peak" } },
  { radical: "足", pinyin: "zú", meaning: "foot", variant: "足", example: { char: "跑", pinyin: "pǎo", meaning: "run" } },
  { radical: "鸟", pinyin: "niǎo", meaning: "bird", variant: "鸟", example: { char: "鸡", pinyin: "jī", meaning: "chicken" } },
  { radical: "疒", pinyin: "nè", meaning: "sickness", variant: "疒", example: { char: "病", pinyin: "bìng", meaning: "illness" } },
  { radical: "辶", pinyin: "chuò", meaning: "walk", variant: "辶", example: { char: "进", pinyin: "jìn", meaning: "enter" } },
  { radical: "衣", pinyin: "yī", meaning: "clothes", variant: "衤", example: { char: "裤", pinyin: "kù", meaning: "pants" } },
  { radical: "犬", pinyin: "quǎn", meaning: "dog", variant: "犭", example: { char: "狗", pinyin: "gǒu", meaning: "dog" } },
  { radical: "目", pinyin: "mù", meaning: "eye", variant: "目", example: { char: "眼", pinyin: "yǎn", meaning: "eye" } },
  { radical: "刀", pinyin: "dāo", meaning: "knife", variant: "刂", example: { char: "到", pinyin: "dào", meaning: "arrive" } },
  { radical: "邑", pinyin: "yì", meaning: "city", variant: "阝", example: { char: "都", pinyin: "dōu", meaning: "all" } },
  { radical: "宀", pinyin: "mián", meaning: "roof", variant: "宀", example: { char: "家", pinyin: "jiā", meaning: "home" } },
  { radical: "禾", pinyin: "hé", meaning: "grain", variant: "禾", example: { char: "秋", pinyin: "qiū", meaning: "autumn" } },
  { radical: "马", pinyin: "mǎ", meaning: "horse", variant: "马", example: { char: "骑", pinyin: "qí", meaning: "ride" } },
  { radical: "贝", pinyin: "bèi", meaning: "shell", variant: "贝", example: { char: "财", pinyin: "cái", meaning: "wealth" } },
  { radical: "车", pinyin: "chē", meaning: "cart", variant: "车", example: { char: "轮", pinyin: "lún", meaning: "wheel" } },
  { radical: "阜", pinyin: "fù", meaning: "hill", variant: "阝", example: { char: "院", pinyin: "yuàn", meaning: "courtyard" } },
  { radical: "示", pinyin: "shì", meaning: "show", variant: "礻", example: { char: "神", pinyin: "shén", meaning: "god" } },
  { radical: "食", pinyin: "shí", meaning: "food", variant: "饣", example: { char: "饭", pinyin: "fàn", meaning: "meal" } },
  { radical: "酉", pinyin: "yǒu", meaning: "alcohol", variant: "酉", example: { char: "酒", pinyin: "jiǔ", meaning: "wine" } },
  { radical: "页", pinyin: "yè", meaning: "head", variant: "页", example: { char: "顶", pinyin: "dǐng", meaning: "top" } },
  { radical: "巾", pinyin: "jīn", meaning: "towel", variant: "巾", example: { char: "帽", pinyin: "mào", meaning: "hat" } },
  { radical: "门", pinyin: "mén", meaning: "gate", variant: "门", example: { char: "间", pinyin: "jiān", meaning: "room" } },
  { radical: "广", pinyin: "yǎn", meaning: "big house", variant: "广", example: { char: "店", pinyin: "diàn", meaning: "shop" } },
  { radical: "米", pinyin: "mǐ", meaning: "rice", variant: "米", example: { char: "粉", pinyin: "fěn", meaning: "powder" } },
  { radical: "田", pinyin: "tián", meaning: "field", variant: "田", example: { char: "男", pinyin: "nán", meaning: "male" } },
  { radical: "彳", pinyin: "chì", meaning: "steps", variant: "彳", example: { char: "很", pinyin: "hěn", meaning: "very" } },
  { radical: "革", pinyin: "gé", meaning: "leather", variant: "革", example: { char: "鞋", pinyin: "xié", meaning: "shoes" } },
  { radical: "戈", pinyin: "gē", meaning: "weapon", variant: "戈", example: { char: "我", pinyin: "wǒ", meaning: "I, me" } },
  { radical: "穴", pinyin: "xué", meaning: "cave", variant: "穴", example: { char: "空", pinyin: "kōng", meaning: "empty" } },
  { radical: "舟", pinyin: "zhōu", meaning: "boat", variant: "舟", example: { char: "船", pinyin: "chuán", meaning: "ship" } },
  { radical: "囗", pinyin: "wéi", meaning: "enclose", variant: "囗", example: { char: "国", pinyin: "guó", meaning: "country" } },
  { radical: "雨", pinyin: "yǔ", meaning: "rain", variant: "雨", example: { char: "雪", pinyin: "xuě", meaning: "snow" } },
  { radical: "厂", pinyin: "hàn", meaning: "shelter", variant: "厂", example: { char: "厅", pinyin: "tīng", meaning: "hall" } },
  { radical: "牛", pinyin: "niú", meaning: "cattle", variant: "牛", example: { char: "物", pinyin: "wù", meaning: "thing" } },
  { radical: "皿", pinyin: "mǐn", meaning: "container", variant: "皿", example: { char: "盘", pinyin: "pán", meaning: "plate" } },
  { radical: "冫", pinyin: "bīng", meaning: "ice", variant: "冫", example: { char: "冷", pinyin: "lěng", meaning: "cold" } },
  { radical: "羽", pinyin: "yǔ", meaning: "feather", variant: "羽", example: { char: "翅", pinyin: "chì", meaning: "wing" } },
  { radical: "子", pinyin: "zǐ", meaning: "baby boy", variant: "子", example: { char: "孩", pinyin: "hái", meaning: "child" } },
  { radical: "骨", pinyin: "gǔ", meaning: "bone", variant: "骨", example: { char: "骼", pinyin: "gé", meaning: "skeleton" } },
  { radical: "毛", pinyin: "máo", meaning: "hair", variant: "毛", example: { char: "毯", pinyin: "tǎn", meaning: "blanket" } },
  { radical: "齿", pinyin: "chǐ", meaning: "teeth", variant: "齿", example: { char: "龄", pinyin: "líng", meaning: "age" } },
  { radical: "爪", pinyin: "zhǎo", meaning: "claw", variant: "爫", example: { char: "爬", pinyin: "pá", meaning: "crawl" } },
  { radical: "走", pinyin: "zǒu", meaning: "walk", variant: "走", example: { char: "起", pinyin: "qǐ", meaning: "rise" } },
  { radical: "舌", pinyin: "shé", meaning: "tongue", variant: "舌", example: { char: "甜", pinyin: "tián", meaning: "sweet" } },
  { radical: "身", pinyin: "shēn", meaning: "body", variant: "身", example: { char: "躺", pinyin: "tǎng", meaning: "lie down" } },
];
